### ISSUE TITLE
Thermostat control

### ISSUE THREAD

**Issue by tpagden** [revenz/openhab#3]
Apologize if this is just a RTFM issue, but the way I understand OH1 to define devices as it pertains to thermostats is through a list of setpoints, sensors, etc. It's not immediately clear to me how to combine these to represent a DevThermostat (1:many).

Below is my OH item definition for a single Z-wave thermostat:

`Number      R01SenThermostatHeatSetPoint    "Heat Set [%.0f F]"                          <thermostat>                         {zwave="14:command=thermostat_setpoint,setpoint_type=1,setpoint_scale=1"}
Number      R01SenThermostatCoolSetPoint    "Cool Set [%.0f F]"                          <thermostat>                         {zwave="14:command=thermostat_setpoint,setpoint_type=2,setpoint_scale=1"}
Number      R01SenThermostatTemperature     "Temperature [%.1f °F]"                      <thermostat>                         {zwave="14:command=sensor_multilevel,sensor_type=1"}
Number      R01SenThermostatMode            "Mode [%d]"                                                                       {zwave="14:command=thermostat_mode"}
Number      R01SenThermostatFan_Mode        "Fan Mode [%d]"                                                                   {zwave="14:command=thermostat_fan_mode"}
Number      R01SenThermostatOperating_State "Opp State [MAP(thermostatOpState.map):%d]"                                       {zwave="14:command=thermostat_operating_state"}
Number      R01SenThermostatFan_State       "Fan State [MAP(thermostatFanState.map):%d]"                                      {zwave="14:command=thermostat_fan_state"}
`

**Comment by revenz** [comment]
This currently isnt support, but its high on my priority list to add support for (I just have got my heatpump system working through openhab so want to add support for this)

**Comment by tpagden** [comment]
Cool thanks - trying to move completely from my devices in Vera.

**Comment by revenz** [comment]
added in beta 2
