### ISSUE TITLE
Imperihab rollershutter item doesn't export stop method

### ISSUE THREAD

**Issue by TheKorn2** [revenz/openhab#4]
Rollershutters (blinds), when exposed to Imperihome via ImperiHab, have up and down buttons but no stop button.  (Stop button is present in openhab and it works, sooOOooo....  yeah.  :D)

**Comment by revenz** [comment]
how have you setup the blinds in openHAB?

I dont have these to test myself, but I'd imagine, its a dimmer item for the shutter and then you want a Switch for stop?

So when stop is pushed in imperiHome the Switch "Stop_Shutters" in openHAB is called with a "ON" command?  then in your rules you would respond to that command?

So something like this?

Dimmer mybinds { imperihab:"type:DevShutter,StopSwitch:myblindsstop" }
Switch myblindsstop

**Comment by TheKorn2** [comment]
Sorry, didn't see you had commented on this!  (was just swinging by to check.  ;) )

In openhab, the item config looks like this:

Rollershutter	LIVINGROOM_PROJECTOR_SCREEN	"Livingroom Projector Screen" (Group_Living_Room, Group_Persistence)  {zwave="105:0:command=SWITCH_MULTILEVEL,refresh_interval=600", imperihab="room:OH_Livingroom,type:DevShutter,label:Projector screen"}

So for type rollershutter within openhab, it automatically presents three buttons...  up, stop, and down.  Imperihab correctly maps up and down, but is missing the stop item.

(i.e. there is no separate "stop" switch, though I suppose I could implement one if I really had to.)

**Comment by TheKorn2** [comment]
![blinds_in_openhab](https://cloud.githubusercontent.com/assets/6579539/13892094/1d10d424-ed23-11e5-84d7-f4b7ceeb9454.png)

**Comment by revenz** [comment]
doing it right now, just setting up a virtual shutter to see if it works.  added "pulsable" aswell, but not sure if I got the command right for this, sending IncreaseDecreaseType.INCREASE and IncreaseDecreaseType.DECREASE for that action

**Comment by TheKorn2** [comment]
Unfortunately I don't know enough to answer your question.  I do know that the previous method worked (when I hit up in imperihab, it went through to openhab OK) and worked similarly for down, it just never showed a down *button* in imperihab.
![screenshot_2016-03-18-16-17-34](https://cloud.githubusercontent.com/assets/6579539/13892399/40b29e7e-ed25-11e5-8c16-1ce3a465ecb6.png)

**Comment by revenz** [comment]
added to beta3 which has now been uploaded

**Comment by TheKorn2** [comment]
Mmmm, updated to beta 3, but no stop button has appeared in imperihome!  Tried reload in imperihome, also tried stopping & restarting openhab (and another reload in imperihome).

**Comment by TheKorn2** [comment]
````
openhab@openhab:/openhab/addons$ ls -l *imperihab*
-rwxrw-r-- 1 openhab openhab   6936 Mar 13 09:52 org.openhab.action.imperihab_1.7.0.201502061908.jar
-rwxrw-r-- 1 openhab openhab 355719 Mar 19  2016 org.openhab.binding.imperihab-1.7.0.201603190959.jar
openhab@openhab:/openhab/addons$ md5sum org.openhab.binding.imperihab-1.7.0.201603190959.jar
479d03b1672d20ecae1deb7fe9a3b968  org.openhab.binding.imperihab-1.7.0.201603190959.jar
````

**Comment by TheKorn2** [comment]
Oh sorry, didn't see your note about stoppable.  Let me go add that.

**Comment by TheKorn2** [comment]
That got me squared away, thanks!  (...and it works, too!)

**Comment by revenz** [comment]
glad to hear it
